### ISSUE TITLE
Using letterparser with nextjs ends with SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ppascualv** [mat-sz/letterparser#11]
Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>

**Comment by mat-sz** [comment]
Looks like your setup does not support ES modules. Also, this is the wrong repository.

**Comment by cbracegirdle** [comment]
Did you find a solution to this @ppascualv ?
