### ISSUE TITLE
Error when parsing strange Content-Type header

### ISSUE THREAD

**Issue by NyaMisty** [mat-sz/letterparser#17]
letterparser currently cannot parse this Content-Type:
```
Content-Type: text/plain; charset = "utf-8"
```
This Content-Type is found in email sent by QQ Mail SMTP server (but don't know how to trigger that exactly)

I checked the code and after `const parameterSplit = parameter.split('=');`, letterparser trimed the header name, but didn't trim the header value, causing the fail

**Comment by mat-sz** [comment]
@NyaMisty 

Hello, thank you for your bug report. The issue has been resolved in version 0.1.6 (published now to npm).

**Comment by NyaMisty** [comment]
Thanks so much for the fast fix!
