### ISSUE TITLE
Support for ReplyTo addresses

### ISSUE THREAD

**Issue by LovingGarlic** [mat-sz/letterparser#18]
Could we get support for a list of ReplyTo addresses as outlined in [RFC2822](https://www.ietf.org/rfc/rfc2822.txt)?

**Comment by mat-sz** [comment]
@LovingGarlic Do you want to have them introduced in the `extract` function or is there something else?

**Comment by LovingGarlic** [comment]
The `extract` function is what I had in mind

**Comment by mat-sz** [comment]
@LovingGarlic Apologies for the delay, published with 0.1.7.

**Comment by LovingGarlic** [comment]
@mat-sz No worries. Thanks for getting it done
