### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dogukanolgun** [mat-sz/letterparser#4]
Hi, the parse works fine but it turns '_' to ' ' ('_' to space).
Later the spaces turn into "%20" in the browser and links fail, images that contain _ fail to load due to incorrect url
Exemple:
https://google.com/abc_de
after extracting
https://google.com/abc de
rendering on browser
https://google.com/abc%20de

**Comment by mat-sz** [comment]
@dogukanolgun I'm unable to reproduce your issue, could you please share the raw e-mail?

**Comment by mat-sz** [comment]
@dogukanolgun I was able to resolve the issue in the [lettercoder](https://github.com/mat-sz/lettercoder) package. The update has been published to NPM.
