### ISSUE TITLE
AMP for Email support

### ISSUE THREAD

**Issue by avigoldman** [mat-sz/letterparser#5]
It'd be awesome to have native support for the `text/x-amp-html` mime part treated like text and HTML.

**Comment by mat-sz** [comment]
I've added support for AMP for Email extraction in 620f807. A new version will be released as soon as #4 is resolved.

**Comment by avigoldman** [comment]
Amazing, thanks!

**Comment by mat-sz** [comment]
@avigoldman The support for AMP is available in 0.0.7.

**Comment by avigoldman** [comment]
Thank you!
